/* =========================================================================
 *  data.js  ―  선택과목 가이드 공용 데이터
 *
 *  ▶ 출처: "2028학년도 모집단위별 반영과목 및 대학별 권장과목 자료집"
 *          (대입정보포털 어디가, 2025.09.30. 기준) PART 02 대학별 권장과목
 *  ▶ 과목명 체계: 2022 개정 교육과정
 *  ▶ 이 파일은 PDF에서 자동 추출/정규화한 것으로, 원문 요약 과정에서
 *     일부 손실(범주형 표기 "국어/영어/수학/과학" 등은 제외)과 계열/학과
 *     정규화 휴리스틱이 적용되어 있습니다. 실제 지원 시 각 대학 모집요강 확인 필수.
 *  ▶ SCHOOL_SUBJECTS(유신고 편제표)는 실제 데이터로 교체 필요한 placeholder.
 * ========================================================================= */

const FACULTIES = ["공학", "자연", "인문", "사회", "의약", "교육", "예체능"];

const UNIVERSITIES = {
  "건국대": { logo: "assets/logos/건국대.png" },
  "경북대": { logo: "assets/logos/경북대.png" },
  "경희대": { logo: "assets/logos/경희대.png" },
  "고려대": { logo: "assets/logos/고려대.png" },
  "국민대": { logo: "assets/logos/국민대.png" },
  "동국대": { logo: "assets/logos/동국대.png" },
  "서울대": { logo: "assets/logos/서울대.png" },
  "서울시립대": { logo: "assets/logos/서울시립대.png" },
  "숭실대": { logo: "assets/logos/숭실대.png" },
  "중앙대": { logo: "assets/logos/중앙대.png" },
  "한양대(ERICA)": { logo: "assets/logos/한양대(ERICA).png" },
};

const SUBJECTS = {
  "경제": { description: "수요·공급, 시장, 국가 경제의 원리를 배운다." },
  "경제 수학": { description: "경제 현상을 수학적으로 분석하는 진로선택 과목." },
  "교육의 이해": { description: "교육의 기초 개념을 이해하는 과목." },
  "국제 관계의 이해": { description: "국제 정치·경제 관계를 이해하는 과목." },
  "기술·가정": { description: "기술과 가정생활 전반을 다루는 과목." },
  "기하": { description: "이차곡선·공간도형·벡터를 다루는 기하 중심 과목." },
  "논리와 사고": { description: "논리적 사고와 추론을 기르는 과목." },
  "논술": { description: "논리적 글쓰기 능력을 기르는 과목." },
  "대수": { description: "방정식·부등식·함수 등 대수 전반을 다루는 수학 일반선택." },
  "데이터 과학": { description: "데이터 분석과 활용을 배우는 과목." },
  "도시의 미래 탐구": { description: "도시 공간과 미래를 탐구하는 지리 과목." },
  "독서와 작문": { description: "다양한 글을 읽고 쓰는 능력을 기르는 과목." },
  "독일어": { description: "독일어 기초 의사소통 능력을 기르는 과목." },
  "동아시아 역사 기행": { description: "동아시아 역사를 답사·기행 관점으로 배우는 과목." },
  "로봇과 공학세계": { description: "로봇과 공학의 세계를 체험·탐구하는 과목." },
  "문학": { description: "문학 작품의 수용과 생산을 배우는 과목." },
  "문학과 영상": { description: "문학과 영상 매체를 함께 다루는 과목." },
  "물리학": { description: "역학·전자기·파동 등 물리의 기본을 다루는 과목." },
  "물질과 에너지": { description: "물질의 상태와 에너지를 다루는 화학 진로선택 과목." },
  "미술": { description: "미술의 기초와 표현·감상을 배우는 과목." },
  "미술 감상과 비평": { description: "미술 작품을 감상하고 비평하는 과목." },
  "미술 창작": { description: "미술 작품을 창작하는 과목." },
  "미적분Ⅰ": { description: "함수의 극한과 미분·적분의 기초를 배우는 과목." },
  "미적분Ⅱ": { description: "초월함수의 미적분 등 심화 미적분을 다루는 과목." },
  "법과 사회": { description: "법의 기본 원리와 사회를 다루는 과목." },
  "보건": { description: "건강과 보건 지식을 배우는 과목." },
  "사회문제 탐구": { description: "사회 문제를 탐구·해결하는 과목." },
  "사회와 문화": { description: "사회 현상과 문화를 탐구 방법과 함께 배운다." },
  "삶과 종교": { description: "삶과 종교의 관계를 성찰하는 과목." },
  "생명과학": { description: "세포·유전·생태 등 생명 현상의 기초를 배운다." },
  "생물의 유전": { description: "유전 원리를 다루는 생명과학 진로선택 과목." },
  "생활과학 탐구": { description: "생활 속 과학 현상을 탐구하는 과목." },
  "세계사": { description: "인류 문명과 세계사의 흐름을 배우는 과목." },
  "세계시민과 지리": { description: "세계 여러 지역과 세계시민 의식을 다루는 지리 과목." },
  "세포와 물질대사": { description: "세포와 물질대사를 다루는 생명과학 진로선택 과목." },
  "스페인어": { description: "스페인어 기초 의사소통 능력을 기르는 과목." },
  "스포츠 문화": { description: "스포츠의 문화적 측면을 다루는 과목." },
  "스포츠과학": { description: "스포츠에 담긴 과학 원리를 배우는 과목." },
  "심화 영어": { description: "심화된 영어 의사소통 능력을 기르는 과목." },
  "심화 영어 독해와 작문": { description: "심화된 영어 독해·작문을 다루는 과목." },
  "여행지리": { description: "여행을 통해 지리를 배우는 진로선택 과목." },
  "역학과 에너지": { description: "힘과 운동, 에너지를 심화하는 물리 진로선택 과목." },
  "영미 문학 읽기": { description: "영미 문학 작품을 영어로 읽는 과목." },
  "영어 독해와 작문": { description: "영어 읽기와 쓰기 능력을 기르는 과목." },
  "영어 발표와 토론": { description: "영어로 발표하고 토론하는 능력을 기르는 과목." },
  "영어Ⅰ": { description: "영어 의사소통 능력을 기르는 일반선택 과목." },
  "영어Ⅱ": { description: "영어Ⅰ에 이어 영어 능력을 심화하는 과목." },
  "운동과 건강": { description: "운동과 건강 관리를 배우는 과목." },
  "윤리문제 탐구": { description: "구체적 윤리 문제를 탐구하는 과목." },
  "윤리와 사상": { description: "동서양 윤리 사상과 사회사상을 배운다." },
  "융합과학 탐구": { description: "여러 과학을 융합해 탐구하는 과목." },
  "인간과 심리": { description: "인간의 마음과 행동을 다루는 심리 교양 과목." },
  "인간과 철학": { description: "인간과 삶에 대한 철학적 사유를 다루는 과목." },
  "인공지능 기초": { description: "AI의 원리와 활용을 개괄적으로 배우는 과목." },
  "인공지능 수학": { description: "인공지능에 쓰이는 수학 개념을 다루는 과목." },
  "인문학과 윤리": { description: "인문학적 관점에서 윤리를 성찰하는 과목." },
  "일본어": { description: "일본어 기초 의사소통 능력을 기르는 과목." },
  "전자기와 양자": { description: "전자기와 양자 현상을 다루는 물리 진로선택 과목." },
  "정보": { description: "프로그래밍과 자료구조 등 컴퓨팅 사고력을 기른다." },
  "정치": { description: "정치 제도와 과정을 배우는 과목." },
  "제2외국어": { description: "제2외국어 기초 의사소통 능력을 기르는 과목." },
  "주제 탐구 독서": { description: "관심 주제를 깊이 있게 읽고 탐구하는 과목." },
  "중국어": { description: "중국어 기초 의사소통 능력을 기르는 과목." },
  "지구과학": { description: "지질·대기·천체 등 지구 시스템의 기초." },
  "지구시스템과학": { description: "지구 시스템을 통합적으로 다루는 과목." },
  "직무 수학": { description: "직업 현장에서 활용하는 수학을 다루는 과목." },
  "직무 영어": { description: "직업 현장에서 쓰는 영어를 다루는 과목." },
  "직무 의사소통": { description: "직업 상황에서의 의사소통을 다루는 과목." },
  "체육1": { description: "운동과 스포츠 활동의 기초를 배우는 과목." },
  "체육2": { description: "체육1에 이어 스포츠 활동을 심화하는 과목." },
  "프랑스어": { description: "프랑스어 기초 의사소통 능력을 기르는 과목." },
  "한국사": { description: "우리나라 역사를 배우는 과목." },
  "한국지리 탐구": { description: "우리 국토의 지리를 탐구하는 과목." },
  "한문": { description: "한자와 한문 기초를 배우는 과목." },
  "한문 고전 읽기": { description: "한문 고전을 읽고 이해하는 과목." },
  "행성우주과학": { description: "행성과 우주를 다루는 지구과학 진로선택 과목." },
  "현대사회와 윤리": { description: "현대 사회의 다양한 윤리 문제를 다루는 과목." },
  "화법과 언어": { description: "화법의 원리와 국어 문법을 배우는 과목." },
  "화학": { description: "물질의 구조와 화학 반응의 기초를 배우는 과목." },
  "화학 반응의 세계": { description: "화학 반응과 평형을 다루는 진로선택 과목." },
  "확률과 통계": { description: "경우의 수, 확률, 통계적 추정을 배우는 과목." },
};

/* =========================================================================
 *  유신고 편제표 (학년별 개별 선택과목군)
 *  - 각 그룹: term(학기) · group(선택과목군 이름) · pick(택N) · credit(학점) · subjects
 *  - curriculum 페이지가 이 구조로 "임시 선택" 폼(택1=라디오, 택N=체크박스)을 그린다.
 *  - SCHOOL_SUBJECTS(개설 과목)는 이 편제표에서 자동 도출된다.
 *  - 2학년: 실제 편제표 반영됨. 1·3학년: 미입력(placeholder).
 *    ※ 예술/심화 트랙(연간)의 학기·군 번호 라벨은 추후 확인 필요.
 * ========================================================================= */
const ABSOLUTE_SUBJECTS = [
  "금융과 경제생활", "여행지리", "역사로 탐구하는 현대 세계", "윤리문제 탐구",
  "융합과학 탐구", "사회문제 탐구", "기후변화와 지속가능한 세계", "과학의 역사와 문화",
]; // 5등급 절대평가 과목 (표기: "(절대)")

const CURRICULUM = {
  "2학년": [
    { term: "1학기", group: "선택과목군1", pick: 1, credit: 3,
      subjects: ["기하", "언어생활과 한자"] },
    { term: "1학기", group: "선택과목군2", pick: 1, credit: 3,
      subjects: ["일본어", "중국어"] },
    { term: "1학기", group: "선택과목군3", pick: 3, credit: 3,
      subjects: ["세계시민과 지리", "사회와 문화", "동아시아 역사 기행", "인문학과 윤리", "금융과 경제생활",
                 "물리학", "화학", "생명과학", "지구과학", "인공지능 기초"] },
    { term: "2학기", group: "선택과목군1", pick: 1, credit: 3,
      subjects: ["인공지능 수학", "한문"] },
    { term: "2학기", group: "선택과목군2", pick: 1, credit: 3,
      subjects: ["일본어 회화", "중국 문화"] },
    { term: "2학기", group: "선택과목군3", pick: 3, credit: 3,
      subjects: ["현대사회와 윤리", "법과 사회", "경제", "여행지리", "역사로 탐구하는 현대 세계",
                 "역학과 에너지", "물질과 에너지", "세포와 물질대사", "지구시스템과학", "인공지능 일반"] },
    { term: "연간", group: "예술 선택1", pick: 1, credit: 3,
      subjects: ["미술 감상과 비평", "음악 감상과 비평"] },
    { term: "연간", group: "예술 선택2", pick: 1, credit: 3,
      subjects: ["미술과 매체", "음악과 미디어"] },
    { term: "연간", group: "진로심화 선택", pick: 3, credit: 3,
      subjects: ["세계사", "한국지리 탐구", "도시의 미래 탐구", "윤리와 사상", "국제 관계의 이해", "윤리문제 탐구",
                 "전자기와 양자", "화학 반응의 세계", "생물의 유전", "행성우주과학", "융합과학 탐구",
                 "프로그래밍", "일본 문화", "중국어 회화", "논술", "기초 체육 전공 실기",
                 "문학과 영상", "미디어 영어", "미적분Ⅱ"] },
    { term: "연간", group: "교양 선택", pick: 2, credit: 2,
      subjects: ["생태와 환경", "인간과 심리", "보건", "인간과 경제활동"] },
    { term: "연간", group: "심화 선택", pick: 3, credit: 3,
      subjects: ["사회문제 탐구", "기후변화와 지속가능한 세계", "과학의 역사와 문화", "소프트웨어와 생활",
                 "심화 일본어", "심화 중국어", "논리와 사고", "심화 체육 전공실기",
                 "매체 의사소통", "세계 문화와 영어", "수학과제 탐구"] },
  ],
  "1학년": [], // TODO: 1학년 편제표 입력 예정
  "3학년": [], // TODO: 3학년 편제표 입력 예정
};

/* 편제표에서 학년별 개설 과목(중복 제거)을 도출 */
function subjectsFromCurriculum(grade) {
  const seen = [];
  (CURRICULUM[grade] || []).forEach((g) =>
    g.subjects.forEach((s) => { if (!seen.includes(s)) seen.push(s); })
  );
  return seen;
}

/* 아직 편제표가 없는 학년용 placeholder (추천 필터가 비지 않도록) */
const _SCHOOL_PLACEHOLDER = ["대수", "미적분Ⅰ", "미적분Ⅱ", "확률과 통계", "기하", "경제 수학", "인공지능 수학", "화법과 언어", "독서와 작문", "문학", "주제 탐구 독서", "문학과 영상", "영어Ⅰ", "영어Ⅱ", "영어 독해와 작문", "영어 발표와 토론", "심화 영어", "심화 영어 독해와 작문", "영미 문학 읽기", "세계시민과 지리", "세계사", "사회와 문화", "현대사회와 윤리", "한국지리 탐구", "동아시아 역사 기행", "정치", "법과 사회", "경제", "윤리와 사상", "인문학과 윤리", "국제 관계의 이해", "물리학", "화학", "생명과학", "지구과학", "역학과 에너지", "전자기와 양자", "물질과 에너지", "화학 반응의 세계", "세포와 물질대사", "생물의 유전", "정보", "인공지능 기초", "기술·가정", "한문", "중국어", "일본어", "미술", "미술 창작", "미술 감상과 비평", "체육1", "체육2", "운동과 건강", "인간과 철학", "논리와 사고", "인간과 심리", "교육의 이해", "삶과 종교", "보건"];

/* 유신고 개설 과목(학년별) — 편제표가 있으면 그것에서, 없으면 placeholder */
const SCHOOL_SUBJECTS = {
  "1학년": (CURRICULUM["1학년"].length ? subjectsFromCurriculum("1학년") : _SCHOOL_PLACEHOLDER),
  "2학년": (CURRICULUM["2학년"].length ? subjectsFromCurriculum("2학년") : _SCHOOL_PLACEHOLDER),
  "3학년": (CURRICULUM["3학년"].length ? subjectsFromCurriculum("3학년") : _SCHOOL_PLACEHOLDER),
};

/* 대학별 권장/핵심 과목 레코드 (레코드 1개 = 대학 × 학과) */
const RECOMMENDATIONS = [
  { university: "건국대", faculty: "공학", major: "건축학과", majorRaw: "건축대학",
    subjects: { core: ["대수", "미적분Ⅰ", "미적분Ⅱ", "확률과 통계"], recommended: [] } },
  { university: "건국대", faculty: "사회", major: "경영학과", majorRaw: "경영대학",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계"], recommended: [] } },
  { university: "건국대", faculty: "사회", major: "부동산대학", majorRaw: "부동산대학",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계"], recommended: [] } },
  { university: "건국대", faculty: "사회", major: "사회과학대학", majorRaw: "사회과학대학",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계"], recommended: [] } },
  { university: "건국대", faculty: "의약", major: "수의예과", majorRaw: "수의과대학",
    subjects: { core: ["대수", "미적분Ⅰ", "미적분Ⅱ", "확률과 통계"], recommended: [] } },
  { university: "건국대", faculty: "자연", major: "생명과학과", majorRaw: "생명과학대학",
    subjects: { core: ["대수", "미적분Ⅰ", "미적분Ⅱ", "확률과 통계"], recommended: [] } },
  { university: "건국대", faculty: "자연", major: "이과대학", majorRaw: "이과대학",
    subjects: { core: ["대수", "미적분Ⅰ", "미적분Ⅱ", "확률과 통계"], recommended: [] } },
  { university: "경북대", faculty: "공학", major: "IT대학", majorRaw: "IT대학",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "물리학", "화학"], recommended: ["미적분Ⅱ", "기하", "역학과 에너지", "전자기와 양자"] } },
  { university: "경북대", faculty: "공학", major: "경제학과", majorRaw: "식품자원경제학과",
    subjects: { core: ["미적분Ⅰ", "확률과 통계"], recommended: ["미적분Ⅱ", "경제"] } },
  { university: "경북대", faculty: "공학", major: "생명과학과", majorRaw: "생명공학부생물학과",
    subjects: { core: ["미적분Ⅰ", "화학", "생명과학"], recommended: ["화학 반응의 세계", "세포와 물질대사", "생물의 유전", "화학"] } },
  { university: "경북대", faculty: "사회", major: "사회과학대학", majorRaw: "사회과학대학",
    subjects: { core: ["사회와 문화", "세계시민과 지리", "현대사회와 윤리", "정치", "인간과 심리"], recommended: ["국제 관계의 이해", "한국지리 탐구", "도시의 미래 탐구", "인문학과 윤리", "문학"] } },
  { university: "경북대", faculty: "의약", major: "간호학과", majorRaw: "간호학과",
    subjects: { core: ["생명과학", "화학"], recommended: ["세포와 물질대사", "생물의 유전", "화학 반응의 세계", "화학"] } },
  { university: "경북대", faculty: "의약", major: "수의예과", majorRaw: "의과대학치과대학수의과대학약학대학",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "물리학", "화학", "생명과학"], recommended: ["미적분Ⅱ", "화학 반응의 세계", "물질과 에너지", "세포와 물질대사", "생물의 유전", "화학"] } },
  { university: "경북대", faculty: "의약", major: "치위생/식품외식산업학과", majorRaw: "치위생/식품외식산업학과",
    subjects: { core: ["화학", "생명과학"], recommended: ["세포와 물질대사", "생물의 유전"] } },
  { university: "경북대", faculty: "인문", major: "고고인류학과", majorRaw: "고고인류학과",
    subjects: { core: ["세계사", "사회와 문화"], recommended: ["동아시아 역사 기행"] } },
  { university: "경북대", faculty: "인문", major: "독어독문학과", majorRaw: "독어독문학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "경북대", faculty: "인문", major: "사학과", majorRaw: "사학과",
    subjects: { core: ["세계사", "사회와 문화"], recommended: ["동아시아 역사 기행"] } },
  { university: "경북대", faculty: "자연", major: "과학기술대학", majorRaw: "과학기술대학",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "물리학", "화학"], recommended: ["미적분Ⅱ", "기하", "역학과 에너지", "전자기와 양자", "물질과 에너지", "화학 반응의 세계", "화학"] } },
  { university: "경북대", faculty: "자연", major: "물리학과", majorRaw: "물리학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "물리학"], recommended: ["미적분Ⅱ", "기하", "인공지능 수학"] } },
  { university: "경북대", faculty: "자연", major: "생명과학과", majorRaw: "농업생명과학대학",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "물리학", "화학", "생명과학"], recommended: ["미적분Ⅱ", "화학 반응의 세계", "세포와 물질대사", "생물의 유전", "물질과 에너지", "화학"] } },
  { university: "경북대", faculty: "자연", major: "생태환경대학", majorRaw: "생태환경대학",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "생명과학", "화학"], recommended: ["세포와 물질대사", "생물의 유전"] } },
  { university: "경북대", faculty: "자연", major: "수학과", majorRaw: "수학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "물리학"], recommended: ["미적분Ⅱ", "기하", "인공지능 수학"] } },
  { university: "경북대", faculty: "자연", major: "식품영양학과", majorRaw: "식품영양학과",
    subjects: { core: ["생명과학", "화학"], recommended: ["세포와 물질대사", "생물의 유전", "물질과 에너지", "화학 반응의 세계", "화학"] } },
  { university: "경북대", faculty: "자연", major: "통계학과", majorRaw: "통계학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "물리학"], recommended: ["미적분Ⅱ", "기하", "인공지능 수학"] } },
  { university: "경북대", faculty: "자연", major: "화학과", majorRaw: "화학과",
    subjects: { core: ["미적분Ⅰ", "화학", "생명과학"], recommended: ["화학 반응의 세계", "세포와 물질대사", "생물의 유전", "화학"] } },
  { university: "경희대", faculty: "공학", major: "건축학과", majorRaw: "건축공학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "물리학"], recommended: ["기하"] } },
  { university: "경희대", faculty: "공학", major: "건축학과", majorRaw: "건축학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계"], recommended: ["미적분Ⅱ", "기하", "물리학"] } },
  { university: "경희대", faculty: "공학", major: "기계공학과", majorRaw: "기계공학부",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "물리학", "화학", "미적분Ⅱ", "기하", "역학과 에너지", "전자기와 양자"], recommended: ["물질과 에너지", "화학 반응의 세계", "화학"] } },
  { university: "경희대", faculty: "공학", major: "사회기반시스템공학과", majorRaw: "사회기반시스템공학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "물리학"], recommended: ["기하"] } },
  { university: "경희대", faculty: "공학", major: "산업공학과", majorRaw: "산업경영공학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ"], recommended: [] } },
  { university: "경희대", faculty: "공학", major: "생명과학과", majorRaw: "식품생명공학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "화학", "생명과학", "세포와 물질대사", "생물의 유전"], recommended: ["미적분Ⅱ", "물질과 에너지", "화학 반응의 세계", "화학"] } },
  { university: "경희대", faculty: "공학", major: "생명과학과", majorRaw: "유전생명공학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "화학", "생명과학", "세포와 물질대사", "생물의 유전"], recommended: ["미적분Ⅱ", "물질과 에너지", "화학 반응의 세계", "화학"] } },
  { university: "경희대", faculty: "공학", major: "생체의공학과", majorRaw: "생체의공학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "물리학", "화학", "미적분Ⅱ", "기하", "역학과 에너지", "전자기와 양자"], recommended: [] } },
  { university: "경희대", faculty: "공학", major: "신소재공학과", majorRaw: "신소재공학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "기하", "물리학", "화학", "물질과 에너지", "역학과 에너지"], recommended: ["전자기와 양자", "화학 반응의 세계", "화학"] } },
  { university: "경희대", faculty: "공학", major: "신소재공학과", majorRaw: "융합바이오·신소재공학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "화학", "생명과학", "세포와 물질대사", "생물의 유전", "물질과 에너지", "화학 반응의 세계"], recommended: ["미적분Ⅱ"] } },
  { university: "경희대", faculty: "공학", major: "원자력공학과", majorRaw: "원자력공학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "기하", "물리학", "화학", "물질과 에너지", "역학과 에너지"], recommended: ["전자기와 양자", "화학 반응의 세계", "화학"] } },
  { university: "경희대", faculty: "공학", major: "인공지능학과", majorRaw: "인공지능학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "기하"], recommended: ["인공지능 수학"] } },
  { university: "경희대", faculty: "공학", major: "전자공학과", majorRaw: "반도체공학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "물리학", "화학", "미적분Ⅱ", "기하", "역학과 에너지", "전자기와 양자"], recommended: [] } },
  { university: "경희대", faculty: "공학", major: "전자공학과", majorRaw: "전자공학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "물리학", "화학", "미적분Ⅱ", "기하", "역학과 에너지", "전자기와 양자"], recommended: [] } },
  { university: "경희대", faculty: "공학", major: "컴퓨터공학과", majorRaw: "소프트웨어융합학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "기하"], recommended: ["인공지능 수학"] } },
  { university: "경희대", faculty: "공학", major: "컴퓨터공학과", majorRaw: "컴퓨터공학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "기하"], recommended: ["인공지능 수학"] } },
  { university: "경희대", faculty: "공학", major: "화학공학과", majorRaw: "화학공학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "물리학", "화학", "미적분Ⅱ", "물질과 에너지", "화학 반응의 세계"], recommended: ["기하", "전자기와 양자", "역학과 에너지"] } },
  { university: "경희대", faculty: "공학", major: "환경학및환경공학과", majorRaw: "환경학및환경공학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "화학", "생명과학", "세포와 물질대사", "생물의 유전"], recommended: ["미적분Ⅱ", "물질과 에너지", "화학 반응의 세계", "화학"] } },
  { university: "경희대", faculty: "사회", major: "지리학과", majorRaw: "지리학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "지구과학"], recommended: [] } },
  { university: "경희대", faculty: "의약", major: "간호학과", majorRaw: "간호학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "생명과학", "세포와 물질대사", "생물의 유전"], recommended: ["미적분Ⅱ", "화학", "물질과 에너지", "화학 반응의 세계"] } },
  { university: "경희대", faculty: "의약", major: "약학과", majorRaw: "약과학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "화학", "생명과학", "물질과 에너지", "화학 반응의 세계", "세포와 물질대사", "생물의 유전"], recommended: ["물리학"] } },
  { university: "경희대", faculty: "의약", major: "약학과", majorRaw: "약학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "화학", "생명과학", "물질과 에너지", "화학 반응의 세계", "세포와 물질대사", "생물의 유전"], recommended: ["물리학"] } },
  { university: "경희대", faculty: "의약", major: "약학과", majorRaw: "한약학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "화학", "생명과학", "물질과 에너지", "화학 반응의 세계", "세포와 물질대사", "생물의 유전"], recommended: ["물리학"] } },
  { university: "경희대", faculty: "의약", major: "의예과", majorRaw: "의예과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "화학", "생명과학", "물질과 에너지", "화학 반응의 세계", "세포와 물질대사", "생물의 유전"], recommended: ["물리학"] } },
  { university: "경희대", faculty: "의약", major: "치의예과", majorRaw: "치의예과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "화학", "생명과학", "세포와 물질대사", "생물의 유전"], recommended: ["물리학", "물질과 에너지", "화학", "화학 반응의 세계"] } },
  { university: "경희대", faculty: "의약", major: "한의예과", majorRaw: "한의예과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "화학", "생명과학", "세포와 물질대사", "생물의 유전"], recommended: ["물리학", "물질과 에너지", "화학", "화학 반응의 세계"] } },
  { university: "경희대", faculty: "자연", major: "물리학과", majorRaw: "물리학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "기하", "물리학", "역학과 에너지", "전자기와 양자"], recommended: ["화학", "물질과 에너지"] } },
  { university: "경희대", faculty: "자연", major: "물리학과", majorRaw: "응용물리학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "기하", "물리학", "역학과 에너지", "전자기와 양자"], recommended: ["화학", "물질과 에너지"] } },
  { university: "경희대", faculty: "자연", major: "미래정보디스플레이학부", majorRaw: "미래정보디스플레이학부",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "물리학", "화학", "미적분Ⅱ", "기하", "역학과 에너지", "전자기와 양자"], recommended: [] } },
  { university: "경희대", faculty: "자연", major: "생명과학과", majorRaw: "생물학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "화학", "생명과학", "세포와 물질대사", "생물의 유전"], recommended: ["미적분Ⅱ", "물리학"] } },
  { university: "경희대", faculty: "자연", major: "수학과", majorRaw: "수학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "기하"], recommended: [] } },
  { university: "경희대", faculty: "자연", major: "수학과", majorRaw: "응용수학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "기하"], recommended: [] } },
  { university: "경희대", faculty: "자연", major: "식품영양학과", majorRaw: "식품영양학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "화학", "생명과학", "세포와 물질대사", "생물의 유전"], recommended: ["미적분Ⅱ", "물질과 에너지", "화학 반응의 세계", "화학"] } },
  { university: "경희대", faculty: "자연", major: "우주과학과", majorRaw: "우주과학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "물리학", "화학", "지구과학", "역학과 에너지", "전자기와 양자"], recommended: ["기하", "지구시스템과학", "행성우주과학"] } },
  { university: "경희대", faculty: "자연", major: "화학과", majorRaw: "응용화학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "화학", "물질과 에너지", "화학 반응의 세계"], recommended: ["기하", "물리학", "생명과학", "역학과 에너지", "전자기와 양자"] } },
  { university: "경희대", faculty: "자연", major: "화학과", majorRaw: "화학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계", "미적분Ⅱ", "화학", "물질과 에너지", "화학 반응의 세계"], recommended: ["기하", "물리학", "생명과학", "역학과 에너지", "전자기와 양자"] } },
  { university: "고려대", faculty: "공학", major: "건축학과", majorRaw: "건축사회환경공학부",
    subjects: { core: [], recommended: ["미적분Ⅱ", "역학과 에너지"] } },
  { university: "고려대", faculty: "공학", major: "건축학과", majorRaw: "건축학과",
    subjects: { core: [], recommended: ["미적분Ⅱ"] } },
  { university: "고려대", faculty: "공학", major: "기계공학과", majorRaw: "기계공학부",
    subjects: { core: [], recommended: ["미적분Ⅱ", "역학과 에너지", "전자기와 양자"] } },
  { university: "고려대", faculty: "공학", major: "산업공학과", majorRaw: "산업경영공학부",
    subjects: { core: [], recommended: ["미적분Ⅱ"] } },
  { university: "고려대", faculty: "공학", major: "생명과학과", majorRaw: "바이오시스템의과학부",
    subjects: { core: [], recommended: ["미적분Ⅱ", "물질과 에너지", "화학 반응의 세계", "세포와 물질대사", "생물의 유전", "화학"] } },
  { university: "고려대", faculty: "공학", major: "생명과학과", majorRaw: "바이오의공학부",
    subjects: { core: [], recommended: ["미적분Ⅱ", "역학과 에너지", "전자기와 양자", "물질과 에너지", "화학 반응의 세계", "세포와 물질대사", "생물의 유전", "화학"] } },
  { university: "고려대", faculty: "공학", major: "생명과학과", majorRaw: "생명공학부",
    subjects: { core: [], recommended: ["미적분Ⅱ", "물질과 에너지", "화학 반응의 세계", "세포와 물질대사", "생물의 유전", "화학"] } },
  { university: "고려대", faculty: "공학", major: "식품공학과", majorRaw: "식품공학과",
    subjects: { core: [], recommended: ["미적분Ⅱ", "물질과 에너지", "화학 반응의 세계", "세포와 물질대사", "생물의 유전", "화학"] } },
  { university: "고려대", faculty: "공학", major: "신소재공학과", majorRaw: "신소재공학부",
    subjects: { core: [], recommended: ["미적분Ⅱ", "역학과 에너지", "전자기와 양자", "물질과 에너지", "화학 반응의 세계", "세포와 물질대사", "생물의 유전", "화학"] } },
  { university: "고려대", faculty: "공학", major: "융합에너지공학과", majorRaw: "융합에너지공학과",
    subjects: { core: [], recommended: ["미적분Ⅱ", "역학과 에너지", "전자기와 양자", "물질과 에너지", "화학 반응의 세계", "세포와 물질대사", "생물의 유전", "화학"] } },
  { university: "고려대", faculty: "공학", major: "인공지능학과", majorRaw: "데이터과학과",
    subjects: { core: [], recommended: ["미적분Ⅱ", "기하"] } },
  { university: "고려대", faculty: "공학", major: "인공지능학과", majorRaw: "인공지능학과",
    subjects: { core: [], recommended: ["미적분Ⅱ", "기하"] } },
  { university: "고려대", faculty: "공학", major: "전자공학과", majorRaw: "반도체공학과",
    subjects: { core: [], recommended: ["미적분Ⅱ", "역학과 에너지", "전자기와 양자"] } },
  { university: "고려대", faculty: "공학", major: "전자공학과", majorRaw: "전기전자공학부",
    subjects: { core: [], recommended: ["미적분Ⅱ", "기하", "역학과 에너지", "전자기와 양자", "물질과 에너지", "화학 반응의 세계", "화학"] } },
  { university: "고려대", faculty: "공학", major: "컴퓨터공학과", majorRaw: "컴퓨터학과",
    subjects: { core: [], recommended: ["미적분Ⅱ", "기하"] } },
  { university: "고려대", faculty: "공학", major: "화학공학과", majorRaw: "화공생명공학과",
    subjects: { core: [], recommended: ["미적분Ⅱ", "기하", "역학과 에너지", "전자기와 양자", "물질과 에너지", "화학 반응의 세계", "화학"] } },
  { university: "고려대", faculty: "공학", major: "환경생태공학부", majorRaw: "환경생태공학부",
    subjects: { core: [], recommended: ["미적분Ⅱ", "물질과 에너지", "화학 반응의 세계", "세포와 물질대사", "생물의 유전", "화학"] } },
  { university: "고려대", faculty: "교육", major: "가정교육과", majorRaw: "가정교육과",
    subjects: { core: [], recommended: ["미적분Ⅱ"] } },
  { university: "고려대", faculty: "교육", major: "수학과", majorRaw: "수학교육과",
    subjects: { core: [], recommended: ["미적분Ⅱ", "기하"] } },
  { university: "고려대", faculty: "의약", major: "간호학과", majorRaw: "간호대학",
    subjects: { core: [], recommended: ["미적분Ⅱ", "물질과 에너지", "화학 반응의 세계", "세포와 물질대사", "생물의 유전", "화학"] } },
  { university: "고려대", faculty: "의약", major: "보건환경융합과학부", majorRaw: "보건환경융합과학부",
    subjects: { core: [], recommended: ["미적분Ⅱ", "물질과 에너지", "화학 반응의 세계", "세포와 물질대사", "생물의 유전", "화학"] } },
  { university: "고려대", faculty: "의약", major: "의과대학", majorRaw: "의과대학",
    subjects: { core: [], recommended: ["미적분Ⅱ", "물질과 에너지", "화학 반응의 세계", "세포와 물질대사", "생물의 유전", "화학"] } },
  { university: "고려대", faculty: "인문", major: "차세대통신학과", majorRaw: "차세대통신학과",
    subjects: { core: [], recommended: ["미적분Ⅱ", "역학과 에너지", "전자기와 양자"] } },
  { university: "고려대", faculty: "자연", major: "물리학과", majorRaw: "물리학과",
    subjects: { core: [], recommended: ["미적분Ⅱ", "역학과 에너지", "전자기와 양자"] } },
  { university: "고려대", faculty: "자연", major: "생명과학과", majorRaw: "생명과학부",
    subjects: { core: [], recommended: ["미적분Ⅱ", "물질과 에너지", "화학 반응의 세계", "세포와 물질대사", "생물의 유전", "화학"] } },
  { university: "고려대", faculty: "자연", major: "수학과", majorRaw: "수학과",
    subjects: { core: [], recommended: ["미적분Ⅱ", "기하"] } },
  { university: "고려대", faculty: "자연", major: "화학과", majorRaw: "화학과",
    subjects: { core: [], recommended: ["미적분Ⅱ", "물질과 에너지", "화학 반응의 세계", "화학"] } },
  { university: "국민대", faculty: "공학", major: "건설시스템공학부", majorRaw: "건설시스템공학부",
    subjects: { core: ["대수", "미적분Ⅰ", "미적분Ⅱ", "물리학"], recommended: ["확률과 통계", "화학"] } },
  { university: "국민대", faculty: "공학", major: "건축학과", majorRaw: "건축학부",
    subjects: { core: ["대수", "미적분Ⅰ", "물리학"], recommended: ["기하", "미적분Ⅱ"] } },
  { university: "국민대", faculty: "공학", major: "기계공학과", majorRaw: "기계공학부",
    subjects: { core: ["미적분Ⅰ", "물리학"], recommended: ["미적분Ⅱ", "기하", "역학과 에너지"] } },
  { university: "국민대", faculty: "공학", major: "생명과학과", majorRaw: "임산생명공학과",
    subjects: { core: ["확률과 통계", "미적분Ⅰ", "화학", "생명과학"], recommended: ["미적분Ⅱ", "세포와 물질대사", "화학 반응의 세계", "생물의 유전", "화학"] } },
  { university: "국민대", faculty: "공학", major: "신소재공학과", majorRaw: "신소재공학부에너지·모빌리티재료전공",
    subjects: { core: ["미적분Ⅰ", "물리학", "화학"], recommended: ["기하", "역학과 에너지", "물질과 에너지"] } },
  { university: "국민대", faculty: "공학", major: "인공지능학과", majorRaw: "AI빅데이터융합경영학과",
    subjects: { core: ["확률과 통계"], recommended: ["미적분Ⅰ"] } },
  { university: "국민대", faculty: "공학", major: "인공지능학과", majorRaw: "인공지능학부",
    subjects: { core: ["확률과 통계", "미적분Ⅰ"], recommended: ["미적분Ⅱ", "기하"] } },
  { university: "국민대", faculty: "공학", major: "자동차융합대학", majorRaw: "자동차융합대학",
    subjects: { core: ["미적분Ⅰ", "물리학"], recommended: ["미적분Ⅱ", "기하"] } },
  { university: "국민대", faculty: "공학", major: "전자공학과", majorRaw: "나노전자물리학과",
    subjects: { core: ["대수", "미적분Ⅰ", "물리학"], recommended: ["역학과 에너지", "전자기와 양자"] } },
  { university: "국민대", faculty: "공학", major: "전자공학과", majorRaw: "신소재공학부전자화학재료전공",
    subjects: { core: ["미적분Ⅰ", "물리학", "화학"], recommended: ["기하", "전자기와 양자", "물질과 에너지"] } },
  { university: "국민대", faculty: "공학", major: "전자공학과", majorRaw: "전자공학부모빌리티전력전자융합전공",
    subjects: { core: ["대수", "미적분Ⅰ", "물리학"], recommended: ["미적분Ⅱ"] } },
  { university: "국민대", faculty: "공학", major: "전자공학과", majorRaw: "전자공학부지능형ICT융합전공",
    subjects: { core: ["대수", "미적분Ⅰ", "물리학"], recommended: ["미적분Ⅱ"] } },
  { university: "국민대", faculty: "공학", major: "전자공학과", majorRaw: "전자공학부지능형반도체융합전자전공",
    subjects: { core: ["대수", "미적분Ⅰ", "물리학"], recommended: ["미적분Ⅱ"] } },
  { university: "국민대", faculty: "공학", major: "컴퓨터공학과", majorRaw: "소프트웨어학부",
    subjects: { core: ["확률과 통계", "미적분Ⅰ"], recommended: ["미적분Ⅱ", "기하"] } },
  { university: "국민대", faculty: "사회", major: "경영학과", majorRaw: "경영정보학부",
    subjects: { core: ["확률과 통계"], recommended: ["미적분Ⅰ"] } },
  { university: "국민대", faculty: "사회", major: "경영학과", majorRaw: "경영학부",
    subjects: { core: ["확률과 통계"], recommended: ["경제 수학", "경제"] } },
  { university: "국민대", faculty: "사회", major: "경제학과", majorRaw: "경제학과",
    subjects: { core: ["미적분Ⅰ", "확률과 통계"], recommended: ["경제 수학", "경제"] } },
  { university: "국민대", faculty: "사회", major: "국제통상학과", majorRaw: "국제통상학과",
    subjects: { core: ["미적분Ⅰ", "확률과 통계"], recommended: [] } },
  { university: "국민대", faculty: "사회", major: "동아시아국제학부", majorRaw: "동아시아국제학부",
    subjects: { core: ["화법과 언어"], recommended: ["동아시아 역사 기행", "국제 관계의 이해"] } },
  { university: "국민대", faculty: "사회", major: "미디어광고학부광고홍보학전공", majorRaw: "미디어광고학부광고홍보학전공",
    subjects: { core: [], recommended: ["문학과 영상", "영어 발표와 토론", "문학"] } },
  { university: "국민대", faculty: "사회", major: "미디어광고학부미디어전공", majorRaw: "미디어광고학부미디어전공",
    subjects: { core: [], recommended: ["확률과 통계"] } },
  { university: "국민대", faculty: "사회", major: "정치외교학과", majorRaw: "정치외교학과",
    subjects: { core: ["사회와 문화"], recommended: ["정치", "법과 사회", "국제 관계의 이해", "확률과 통계"] } },
  { university: "국민대", faculty: "인문", major: "사학과", majorRaw: "한국역사학과",
    subjects: { core: ["한국사"], recommended: ["세계사", "한문"] } },
  { university: "국민대", faculty: "인문", major: "중어중문학과", majorRaw: "중어중문학과",
    subjects: { core: ["중국어"], recommended: ["한문 고전 읽기", "중국어", "한문"] } },
  { university: "국민대", faculty: "자연", major: "생명과학과", majorRaw: "응용화학부 바이오 의약전공",
    subjects: { core: ["화학", "생명과학"], recommended: ["세포와 물질대사", "생물의 유전", "화학 반응의 세계", "화학"] } },
  { university: "국민대", faculty: "자연", major: "응용화학부 나노 소재전공", majorRaw: "응용화학부 나노 소재전공",
    subjects: { core: ["미적분Ⅰ", "화학"], recommended: ["인공지능 수학", "물질과 에너지", "화학 반응의 세계", "화학"] } },
  { university: "국민대", faculty: "자연", major: "컴퓨터공학과", majorRaw: "정보보안암호수학과",
    subjects: { core: ["대수", "미적분Ⅰ", "확률과 통계"], recommended: ["기하", "미적분Ⅱ"] } },
  { university: "동국대", faculty: "공학", major: "건설환경공학과", majorRaw: "건설환경공학과",
    subjects: { core: ["물리학", "화학"], recommended: ["지구과학"] } },
  { university: "동국대", faculty: "공학", major: "건축학과", majorRaw: "건축공학부",
    subjects: { core: ["물리학"], recommended: [] } },
  { university: "동국대", faculty: "공학", major: "기계공학과", majorRaw: "기계로봇에너지공학과",
    subjects: { core: ["물리학", "화학"], recommended: [] } },
  { university: "동국대", faculty: "공학", major: "산업시스템공학과", majorRaw: "산업시스템공학과",
    subjects: { core: [], recommended: ["물리학"] } },
  { university: "동국대", faculty: "공학", major: "생명과학과", majorRaw: "바이오시스템대학",
    subjects: { core: ["화학", "생명과학"], recommended: [] } },
  { university: "동국대", faculty: "공학", major: "신소재공학과", majorRaw: "에너지신소재공학과",
    subjects: { core: ["물리학", "화학"], recommended: [] } },
  { university: "동국대", faculty: "공학", major: "열린전공학부", majorRaw: "열린전공학부",
    subjects: { core: [], recommended: ["제2외국어", "물리학", "화학"] } },
  { university: "동국대", faculty: "공학", major: "인공지능학과", majorRaw: "의료인공지능공학과",
    subjects: { core: ["물리학"], recommended: [] } },
  { university: "동국대", faculty: "공학", major: "전자공학과", majorRaw: "시스템반도체학부",
    subjects: { core: ["물리학", "화학"], recommended: [] } },
  { university: "동국대", faculty: "공학", major: "전자공학과", majorRaw: "전자전기공학부",
    subjects: { core: ["물리학", "화학"], recommended: [] } },
  { university: "동국대", faculty: "공학", major: "컴퓨터공학과", majorRaw: "정보통신공학과",
    subjects: { core: ["물리학"], recommended: [] } },
  { university: "동국대", faculty: "공학", major: "화학공학과", majorRaw: "화공생물공학과",
    subjects: { core: [], recommended: ["생명과학"] } },
  { university: "동국대", faculty: "교육", major: "가정교육과", majorRaw: "가정교육과",
    subjects: { core: ["화학", "기술·가정"], recommended: ["생명과학", "정보"] } },
  { university: "동국대", faculty: "의약", major: "생명과학과", majorRaw: "의생명공학과",
    subjects: { core: ["물리학", "화학"], recommended: ["생명과학"] } },
  { university: "동국대", faculty: "의약", major: "약학과", majorRaw: "약학과",
    subjects: { core: ["화학", "생명과학"], recommended: ["물리학"] } },
  { university: "동국대", faculty: "인문", major: "국어국문학과", majorRaw: "국어국문·문예창작학부",
    subjects: { core: [], recommended: ["한문"] } },
  { university: "동국대", faculty: "인문", major: "사학과", majorRaw: "사학과",
    subjects: { core: [], recommended: ["한문"] } },
  { university: "동국대", faculty: "인문", major: "중어중문학과", majorRaw: "중어중문학과",
    subjects: { core: ["중국어"], recommended: [] } },
  { university: "동국대", faculty: "인문", major: "철학과", majorRaw: "철학과",
    subjects: { core: [], recommended: ["한문"] } },
  { university: "동국대", faculty: "자연", major: "생명과학과", majorRaw: "생명과학과",
    subjects: { core: [], recommended: ["물리학"] } },
  { university: "동국대", faculty: "자연", major: "화학과", majorRaw: "화학과",
    subjects: { core: ["물리학", "화학"], recommended: ["생명과학"] } },
  { university: "서울대", faculty: "공학", major: "건설환경도시공학부", majorRaw: "건설환경도시공학부",
    subjects: { core: [], recommended: ["기하", "미적분Ⅱ"] } },
  { university: "서울대", faculty: "공학", major: "기계공학과", majorRaw: "기계공학부",
    subjects: { core: ["물리학"], recommended: [] } },
  { university: "서울대", faculty: "공학", major: "생명과학과", majorRaw: "바이오시스템·소재학부",
    subjects: { core: [], recommended: ["기하", "미적분Ⅱ"] } },
  { university: "서울대", faculty: "공학", major: "생명과학과", majorRaw: "식품·동물생명공학부",
    subjects: { core: [], recommended: ["기하", "미적분Ⅱ"] } },
  { university: "서울대", faculty: "공학", major: "스마트시스템과학과", majorRaw: "스마트시스템과학과",
    subjects: { core: [], recommended: ["기하", "미적분Ⅱ"] } },
  { university: "서울대", faculty: "공학", major: "원자핵공학과", majorRaw: "원자핵공학과",
    subjects: { core: ["물리학"], recommended: [] } },
  { university: "서울대", faculty: "공학", major: "전자공학과", majorRaw: "전기·정보공학부",
    subjects: { core: ["물리학"], recommended: [] } },
  { university: "서울대", faculty: "공학", major: "조경·지역시스템공학부", majorRaw: "조경·지역시스템공학부",
    subjects: { core: [], recommended: ["기하", "미적분Ⅱ"] } },
  { university: "서울대", faculty: "공학", major: "조선해양공학과", majorRaw: "조선해양공학과",
    subjects: { core: ["물리학"], recommended: [] } },
  { university: "서울대", faculty: "공학", major: "항공우주공학과", majorRaw: "항공우주공학과",
    subjects: { core: ["물리학"], recommended: [] } },
  { university: "서울대", faculty: "교육", major: "교육학과", majorRaw: "교육학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "교육", major: "국어교육과", majorRaw: "국어교육과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "교육", major: "독어교육과", majorRaw: "독어교육과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "교육", major: "물리학과", majorRaw: "물리교육과",
    subjects: { core: ["물리학"], recommended: [] } },
  { university: "서울대", faculty: "교육", major: "불어교육과", majorRaw: "불어교육과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "교육", major: "사학과", majorRaw: "역사교육과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "교육", major: "사회교육과", majorRaw: "사회교육과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "교육", major: "생명과학과", majorRaw: "생물교육과",
    subjects: { core: ["생명과학"], recommended: [] } },
  { university: "서울대", faculty: "교육", major: "수학과", majorRaw: "수학교육과",
    subjects: { core: [], recommended: ["기하", "미적분Ⅱ"] } },
  { university: "서울대", faculty: "교육", major: "영어교육과", majorRaw: "영어교육과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "교육", major: "윤리교육과", majorRaw: "윤리교육과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "교육", major: "지구과학과", majorRaw: "지구과학교육과",
    subjects: { core: ["지구과학"], recommended: [] } },
  { university: "서울대", faculty: "교육", major: "지리교육과", majorRaw: "지리교육과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "교육", major: "화학교육과", majorRaw: "화학교육과",
    subjects: { core: ["화학"], recommended: [] } },
  { university: "서울대", faculty: "사회", major: "경영학과", majorRaw: "경영학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "사회", major: "경제학과", majorRaw: "경제학부",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "사회", major: "경제학과", majorRaw: "농경제사회학부",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "사회", major: "사회복지학과", majorRaw: "사회복지학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "사회", major: "사회학과", majorRaw: "사회학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "사회", major: "소비자아동학부소비자학전공", majorRaw: "소비자아동학부소비자학전공",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "사회", major: "소비자아동학부아동가족학전공", majorRaw: "소비자아동학부아동가족학전공",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "사회", major: "심리학과", majorRaw: "심리학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "사회", major: "언론정보학과", majorRaw: "언론정보학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "사회", major: "인류학과", majorRaw: "인류학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "사회", major: "정치외교학부", majorRaw: "정치외교학부",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "사회", major: "지리학과", majorRaw: "지리학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "예체능", major: "사학과", majorRaw: "고고미술사학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "예체능", major: "의류학과", majorRaw: "의류학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "의약", major: "간호학과", majorRaw: "간호대학",
    subjects: { core: [], recommended: ["미적분Ⅱ", "기하"] } },
  { university: "서울대", faculty: "의약", major: "수의예과", majorRaw: "수의예과",
    subjects: { core: [], recommended: ["기하", "미적분Ⅱ"] } },
  { university: "서울대", faculty: "의약", major: "약학과", majorRaw: "약학과",
    subjects: { core: ["화학", "생명과학"], recommended: ["기하", "미적분Ⅱ"] } },
  { university: "서울대", faculty: "의약", major: "의예과", majorRaw: "의예과",
    subjects: { core: ["생명과학"], recommended: ["기하", "미적분Ⅱ"] } },
  { university: "서울대", faculty: "의약", major: "치의예과", majorRaw: "치의학과",
    subjects: { core: [], recommended: ["미적분Ⅱ", "기하"] } },
  { university: "서울대", faculty: "인문", major: "국어국문학과", majorRaw: "국어국문학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "인문", major: "노어노문학과", majorRaw: "노어노문학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "인문", major: "독어독문학과", majorRaw: "독어독문학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "인문", major: "미학과", majorRaw: "미학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "인문", major: "불어불문학과", majorRaw: "불어불문학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "인문", major: "사학과", majorRaw: "역사학부",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "인문", major: "서어서문학과", majorRaw: "서어서문학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "인문", major: "아시아언어문명학부", majorRaw: "아시아언어문명학부",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "인문", major: "언어학과", majorRaw: "언어학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "인문", major: "영어영문학과", majorRaw: "영어영문학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "인문", major: "종교학과", majorRaw: "종교학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "인문", major: "중어중문학과", majorRaw: "중어중문학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "인문", major: "철학과", majorRaw: "철학과",
    subjects: { core: ["한문", "제2외국어"], recommended: [] } },
  { university: "서울대", faculty: "자연", major: "물리학과", majorRaw: "물리·천문학부물리학전공",
    subjects: { core: ["물리학"], recommended: ["기하", "미적분Ⅱ"] } },
  { university: "서울대", faculty: "자연", major: "물리학과", majorRaw: "물리·천문학부천문학전공",
    subjects: { core: ["지구과학"], recommended: [] } },
  { university: "서울대", faculty: "자연", major: "산림과학부", majorRaw: "산림과학부",
    subjects: { core: [], recommended: ["기하", "미적분Ⅱ"] } },
  { university: "서울대", faculty: "자연", major: "생명과학과", majorRaw: "생명과학부",
    subjects: { core: ["생명과학"], recommended: [] } },
  { university: "서울대", faculty: "자연", major: "생명과학과", majorRaw: "응용생물화학부",
    subjects: { core: [], recommended: ["기하", "미적분Ⅱ"] } },
  { university: "서울대", faculty: "자연", major: "식품영양학과", majorRaw: "식품영양학과",
    subjects: { core: ["한문", "제2외국어"], recommended: ["기하", "미적분Ⅱ"] } },
  { university: "서울대", faculty: "자연", major: "지구과학과", majorRaw: "지구환경과학부",
    subjects: { core: ["지구과학"], recommended: [] } },
  { university: "서울대", faculty: "자연", major: "화학부", majorRaw: "화학부",
    subjects: { core: ["화학"], recommended: [] } },
  { university: "서울시립대", faculty: "공학", major: "공간정보공학과", majorRaw: "공간정보공학과",
    subjects: { core: ["지구과학", "물리학"], recommended: [] } },
  { university: "서울시립대", faculty: "공학", major: "컴퓨터공학과", majorRaw: "전자전기컴퓨터공학부",
    subjects: { core: ["물리학"], recommended: [] } },
  { university: "서울시립대", faculty: "공학", major: "환경공학부", majorRaw: "환경공학부",
    subjects: { core: [], recommended: ["화학", "물리학"] } },
  { university: "숭실대", faculty: "공학", major: "건축학과", majorRaw: "건축학부",
    subjects: { core: ["물리학"], recommended: [] } },
  { university: "숭실대", faculty: "공학", major: "신소재공학과", majorRaw: "신소재공학과",
    subjects: { core: ["화학"], recommended: [] } },
  { university: "숭실대", faculty: "공학", major: "전자공학과", majorRaw: "전기공학부",
    subjects: { core: ["물리학"], recommended: [] } },
  { university: "숭실대", faculty: "공학", major: "전자공학과", majorRaw: "전자정보공학부",
    subjects: { core: ["물리학"], recommended: [] } },
  { university: "숭실대", faculty: "공학", major: "화학공학과", majorRaw: "화학공학과",
    subjects: { core: ["화학"], recommended: [] } },
  { university: "숭실대", faculty: "의약", major: "의생명시스템학부", majorRaw: "의생명시스템학부",
    subjects: { core: ["생명과학"], recommended: [] } },
  { university: "숭실대", faculty: "자연", major: "물리학과", majorRaw: "물리학과",
    subjects: { core: ["물리학"], recommended: [] } },
  { university: "숭실대", faculty: "자연", major: "화학과", majorRaw: "화학과",
    subjects: { core: ["화학"], recommended: [] } },
  { university: "중앙대", faculty: "공학", major: "기계공학과", majorRaw: "기계공학부",
    subjects: { core: ["미적분Ⅱ", "기하", "물리학", "화학", "역학과 에너지", "전자기와 양자"], recommended: [] } },
  { university: "중앙대", faculty: "공학", major: "사회기반시스템공학부", majorRaw: "사회기반시스템공학부",
    subjects: { core: ["미적분Ⅱ", "기하", "물리학", "화학", "역학과 에너지", "전자기와 양자"], recommended: [] } },
  { university: "중앙대", faculty: "공학", major: "에너지시스템공학부첨단소재공학과", majorRaw: "에너지시스템공학부첨단소재공학과",
    subjects: { core: ["미적분Ⅱ", "기하", "물리학", "화학", "물질과 에너지", "화학 반응의 세계"], recommended: [] } },
  { university: "중앙대", faculty: "공학", major: "융합공학부", majorRaw: "융합공학부",
    subjects: { core: ["미적분Ⅱ", "기하", "화학", "물리학", "생명과학", "물질과 에너지", "화학 반응의 세계"], recommended: [] } },
  { university: "중앙대", faculty: "공학", major: "전자공학과", majorRaw: "전자전기공학부",
    subjects: { core: ["미적분Ⅱ", "기하", "물리학", "화학", "역학과 에너지", "전자기와 양자"], recommended: [] } },
  { university: "중앙대", faculty: "공학", major: "전자공학과", majorRaw: "지능형반도체공학과",
    subjects: { core: ["미적분Ⅱ", "기하", "물리학", "화학", "역학과 에너지", "전자기와 양자"], recommended: [] } },
  { university: "중앙대", faculty: "공학", major: "화학공학과", majorRaw: "화학공학과",
    subjects: { core: ["미적분Ⅱ", "기하", "물리학", "화학", "물질과 에너지", "화학 반응의 세계"], recommended: [] } },
  { university: "중앙대", faculty: "자연", major: "물리학과", majorRaw: "물리학과",
    subjects: { core: ["미적분Ⅱ", "기하", "물리학", "화학", "역학과 에너지", "전자기와 양자"], recommended: [] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "건설환경공학과", majorRaw: "건설환경공학과",
    subjects: { core: [], recommended: ["미적분Ⅰ", "물리학", "화학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "건축학과", majorRaw: "건축IT융합전공",
    subjects: { core: [], recommended: ["대수", "확률과 통계", "물리학", "화학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "건축학과", majorRaw: "건축학부",
    subjects: { core: [], recommended: ["대수", "미적분Ⅰ", "물리학", "화학", "지구과학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "건축학과", majorRaw: "스마트건축구조시공융합전공",
    subjects: { core: [], recommended: ["확률과 통계", "물리학", "화학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "교통·물류공학과", majorRaw: "교통·물류공학과",
    subjects: { core: [], recommended: ["미적분Ⅰ", "확률과 통계"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "국방전략기술공학과", majorRaw: "국방전략기술공학과",
    subjects: { core: [], recommended: ["물리학", "지구과학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "기계공학과", majorRaw: "기계공학과",
    subjects: { core: [], recommended: ["미적분Ⅰ", "물리학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "로봇공학과", majorRaw: "로봇공학과",
    subjects: { core: [], recommended: ["미적분Ⅰ", "확률과 통계", "물리학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "로봇융합전공", majorRaw: "로봇융합전공",
    subjects: { core: [], recommended: ["대수", "미적분Ⅰ", "물리학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "산업공학과", majorRaw: "산업경영공학과",
    subjects: { core: [], recommended: ["미적분Ⅰ", "확률과 통계"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "생명과학과", majorRaw: "바이오나노공학전공",
    subjects: { core: [], recommended: ["미적분Ⅰ", "확률과 통계", "화학", "생명과학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "생명과학과", majorRaw: "에너지바이오학과",
    subjects: { core: [], recommended: ["미적분Ⅰ", "확률과 통계", "화학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "소재부품융합전공", majorRaw: "소재부품융합전공",
    subjects: { core: [], recommended: ["미적분Ⅰ", "확률과 통계", "물리학", "화학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "스마트ICT융합전공", majorRaw: "스마트ICT융합전공",
    subjects: { core: [], recommended: ["대수", "확률과 통계", "미적분Ⅰ", "물리학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "융합시스템공학과", majorRaw: "융합시스템공학과",
    subjects: { core: [], recommended: ["대수"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "인공지능학과", majorRaw: "인공지능학과",
    subjects: { core: [], recommended: ["미적분Ⅰ", "확률과 통계"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "전자공학과", majorRaw: "반도체·디스플레이공학전공",
    subjects: { core: [], recommended: ["미적분Ⅰ", "물리학", "화학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "전자공학과", majorRaw: "신소재·반도체공학전공",
    subjects: { core: [], recommended: ["미적분Ⅰ", "확률과 통계", "물리학", "화학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "전자공학과", majorRaw: "전자공학부",
    subjects: { core: [], recommended: ["대수", "미적분Ⅰ", "물리학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "전자공학과", majorRaw: "차세대반도체융합공학부",
    subjects: { core: [], recommended: ["미적분Ⅰ", "확률과 통계", "물리학", "화학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "지능정보양자공학전공", majorRaw: "지능정보양자공학전공",
    subjects: { core: [], recommended: ["미적분Ⅰ", "확률과 통계", "물리학", "지구과학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "컴퓨터공학과", majorRaw: "컴퓨터학부",
    subjects: { core: [], recommended: ["미적분Ⅰ", "확률과 통계"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "해양융합공학과", majorRaw: "해양융합공학과",
    subjects: { core: [], recommended: ["미적분Ⅰ", "확률과 통계", "화학", "지구과학"] } },
  { university: "한양대(ERICA)", faculty: "공학", major: "화학공학과", majorRaw: "배터리소재화학공학과",
    subjects: { core: [], recommended: ["대수", "미적분Ⅰ", "물리학", "화학"] } },
  { university: "한양대(ERICA)", faculty: "의약", major: "약학과", majorRaw: "약학과",
    subjects: { core: [], recommended: ["화학", "생명과학"] } },
];
